services:
  - type: web
    name: blvck-download
    env: node
    buildCommand: npm install && pip install --upgrade yt-dlp requests
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
