services:
  - type: web
    name: blvck-download
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && apt-get update && apt-get install -y python3 python3-pip ffmpeg && pip3 install yt-dlp requests
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
